### ISSUE TITLE
[오프라인] 1차 스터디 안내

### ISSUE THREAD

**Issue by tea7day** [nomins/codespitz#2]
## 일정 (오프라인)
- 2/24(토) `오후 5시`
- 잠실: 한적하고 분위기 좋은 카페

## 진행 내용
- [코드스피츠 73 - 1회차 2편(1/2,2/2) 리뷰](https://www.youtube.com/watch?v=kG87PONfqkg&list=PLBA53uNlbf-tKPtxR85LmXFYk0pNF8-Og&index=8) 
- 진행자: 
   - `1회차 1/2` => `덕주`
   - `1회차 2/2` => `승현`

## 참가자
- 승현, 원종, 덕주

**Comment by tea7day** [comment]
### 승현 - 요약정리
1/2 - Sync Flow
sync flow 
- 메모리의 코드/데이터가 CPU가 계속 소비되고 있는 형태
- 플로우의 방향은 구현자의 마음대로 (초기에는 수학자)
- 

flow vs subflow
routine vs subroutine vs coroutine

언어적인 스팩은 인간을 위한것이고 구현자의 취향이 반영되어있다 
-> 코드를 구현할때는 의도를 충분히 드러나도록 문과 식을 올바르게 써서 알고리즘을 표현하자.
이것은 변수명에 달린 일이 아니다.

if 문이 중요한 이유는 인간의 사고방식은 이진법에 제일 적합하다. (폰노이만)

팁
- 연산자에 괄호치기ㄴㄴ
- if문 보다 else가 중요하다. (optional/mandatory)

## 궁금한 점
자바9의 코루틴

routine vs subroutine vs coroutine

if 문의 실제 스펙은 어떻게 정의되어 있는가
=>
누군가가 스펙을 알려줘야하는가. 내가 스펙을 보고 확인할 수 있는가.
=> 언어의 스펙은 어떻게 보는가

**Comment by deokju** [comment]
# nomi's codespitz 73 1회-1
이 스터디는 프로그래밍의 기초를 단단히 하고 좋은 프로그래머가 되기위해 시작 하였습니다.

## 프로그램이란?

컴퓨터 메모리에 적재되어 실행이 되는것.
실행되어지는것을 만드는이가 **프로그래머**

##  Compile Language 프로그램이 생성되어 사라지기까지의 과정

|      과정명            		|example						|  오류 영역						|
|-------------------------------|-----------------------------  |-----------------------------  |
|LANGUAGE CODE                  | C,JAVA,C++					| LINT TIME						|		
|MACHINE LANGUAGE               | 흔히 말하는 기계어				| COMPILE TIME					|		
|FILE							| main.class, main.cpp			| -								|		
|LOAD							| 컴퓨터 메모리에 적재됨			| -								|		
|RUN							| LOAD 된 프로그램을 실행함		| RUN TIME						|		
|TERMINATE						| 메모리에서 프로그램이 사라짐		| -								|		

**LANGUAGE CODE**.
> 사람이 개발을 하기위해서 영어,숫자, 기호를 조합하여 작성한다. 

**MACHINE LANGUAGE**.
> 사람이 작성한 언어는 기계가 알아들을수 없으므로 기계어로 변환하는 가정을 거친다.
> **사람이 바로 기계어로 작성하지 않는 이유는 기계어로 개발하는게 불편하고 힘들기 때문이다.**

**FILE**.
> compile이 완료되어 파일 1개로 떨어진다.

**LOAD**.
> compile이 완료되어 파일이 메모리에 적재된다.

**RUN**.
> 실행

**TERMINATE**.
> 종료

##  Script Language 프로그램이 생성되어 사라지기까지의 과정

|      과정명            		|example						|  오류 영역						|
|-------------------------------|-----------------------------  |-----------------------------  |
|LANGUAGE CODE                  | javascript					| LINT TIME						|		
|FILE							| main.js						| -								|		
|LOAD							| 컴퓨터 메모리에 적재됨(브라우저가 읽음)			| -								|		
|`MACHINE LANGUAGE`             | 브라우저에 있는 엔진이 일부분 파싱	| COMPILE TIME					|	
|RUN							| LOAD 된 프로그램을 실행함		| RUN TIME						|		
|TERMINATE						| 메모리에서 프로그램이 사라짐		| -								|		
	
**LANGUAGE CODE**
> 사람이 개발을 하기위해서 영어,숫자, 기호를 조합하여 작성한다. 

**FILE**
>  사람이 작성한 JS 파일

**LOAD**
> 웹브라우저(크롬, 파이어폭스)에서 js 파일을 읽는다.

**MACHINE LANGUAGE**
> Load가 된 파일에서 실행하는 부분만을 컴파일(?)한다. 그래서 **부분** 컴파일을 한다고 한다.
>
**RUN**
> 실행

**TERMINATE**
> 종료	

## LEXICAL GRAMMAR
**CONTROL CHARACTER**  **제어문자**
> ???????????????????

**white space**  **공백문자**
> 공백으로 인식되는 문자.

|유니코드     	|이름				|
|-------------- |--------------|
|\u0009     | Tab				|
|\u000B		| Vertical Tab						|
|\u000C		| Form Feed	|
|\u0020     | Space	|

**LINE TERMINATORS**  **개행 문자**
> 흔히 줄바꿈 혹은 엔터값으로 알고 있는 문자값
> \u000D - Carriage Return

**COMMENTS**  **개행 문자**
> 주석 부분 이부분은 자바스크립트 엔진이 주석으로 간주하는 부분

**KEYWORD**  **예약어**
> 자바스크립트언어에서 선점한 단어 및 어휘

|     			|				|				|			  |				 |
|-------------- |--------------|--------------  |--------------|-------------|
|break		    | 기본값		   | 함수		    |return		  | var			 |
|case     		| delete	   | if		   		|switch		  | void		 |
|catch     		| do		   | in		        |this		  | while		 |
|const     		| else		   | instanceof		|throw		  | with		 |
|continue		| finally	   | let		    |try		  | 			 |
|debugger		| for		   | new		    |typeof		  | 			 |


**LITERAL**  
> 값을 **최소**로 표현한것
> 코드상에 직접 값을 표현하는것
	>> 숫자 37를 표현하는 방법
	>> 37 **LITERAL**
	>> 30 +7	
	>> 10 + 10+ 10 + 7

## LANGUAGE  ELEMENT

**STATEMENTS**  **문**
>**문의 종류**
>**공문** ` //아무것도 없음`
>**식문**` 4+2+3 // 식문은 연산식을 포함한다.`
>**제어문**  `for, if, if else //등등`
>**선언문**  `let a = 1; var b = 2;`
>**단문** `console.log(a); console.log(b)`
>>**중문** `{//중괄호 안에 쓰면 됨}`

**EXPRESSION**  **식**
> `expression` 단어를 해석하면 `표현` 이 되는데 이게 적절한 해석은 아니다.
> 여기서 말하는 `expression`은 값으로 최종적으로 값이 되는것을 의미한다.
> 값만 있는 값식이 있을 수 있고 이 값식들을 서로 연산하는 연산식이 될 수도 있다.
> 그리고 호출식도 여기에 해당한다.
`4;`
`4 + 3 + 2;`
`function nomi(){return 5};`
`4 + nomi()` or `nomi()`

**IDENTIFIER**  **식별자**
> 변수가 IDENTIFIER에 해당한다.
> 변수의 의미
**~~값을 담는 그릇~~**

값이 저장되어 있는 메모리의 alias
>> `ex) let a = 18` 숫자 18이라는 값이 저장되어 있는 메모리 주소를 별칭을 a라 한다.

해당 값의 type 정보를 가지고 있다.
>> `ex) typeof a;` 
>> `number가 출력됨;`

변수의 type(종류)에는 2가지가 존재.

 - primitive type(값의 형태)
|Boolean		| Null		   | Undefined		|Number		  | String		| Symbol(ES6이후)|
 >> 변수에 값을 할당 할때 복사를 통해서 이루어진다.

    let a = 4;
    let b = a;
    //a,b 출력
    console.log(a);  // 4출력
    console.log(b); // 4출력
    b = 18;
    console.log(a); // 4출력
    console.log(b); // 18출력

>> a의 메모리 별칭이 b에 할당 되는것이 아니라 a가 가리키고 있는 곳의 값을 복사하여 변수 b에 할당하는 방식이다.
 - reference type(참조의 형태)
> primitive type 이외의 모든것이 참조 타입이 된다.
> 참조 타입의 경우에는 **~~값복사~~**가 아닌 말 그대로 참조 형태가 된다.

    var a = [1,2,3,4,5];
    var b = a;
    console.log(a); //[1,2,3,4,5] 출력
    console.log(b); //[1,2,3,4,5] 출력
    b[0] = 18;		 // b배열 0번째 요소에 18를 대입
    console.log(a); //[18,2,3,4,5] 출력

>이와 같이 참조 타입은 값이 아닌 값을 가리키는 alias 를 복사한다.
