### ISSUE TITLE
[온라인] 2차 스터디 안내

### ISSUE THREAD

**Issue by tea7day** [nomins/codespitz#3]
## 일정 (온라인)
- 3/2(금) `오후 9시 ~ 12시 (3시간)`

## 사전 준비사항
- 화상채팅 프로그램 설치
  - [TeamViewer](https://www.teamviewer.com/en/download/windows/), [Skype](http://skype.daesung.com/eng/main.asp), [Hangout](https://hangouts.google.com/)
- 마이크 또는 마이크 되는 이어폰

## 진행 내용
- [코드스피츠 73 - 2회차 (1/2) 리뷰](https://www.youtube.com/watch?v=q9j6XLOQYeA&index=6&list=PLBA53uNlbf-tKPtxR85LmXFYk0pNF8-Og) - `승현`
- [코드스피츠 73 - 2회차 (2/2) 리뷰](https://www.youtube.com/watch?v=U6dmAT8KImY&index=5&list=PLBA53uNlbf-tKPtxR85LmXFYk0pNF8-Og) - `원종`
- [코드스피츠 73 - 3회차 리뷰](https://www.youtube.com/watch?v=GhAkc00TvZs&index=4&list=PLBA53uNlbf-tKPtxR85LmXFYk0pNF8-Og) - `덕주`

## 참가 예정자
- 승현, 원종, 덕주

**Comment by tea7day** [comment]
### 정리 (작성중)
- Label, Breake, Continue
  - Label Identifier:
  - Breake Label;
  - Continue Label;

- Label은 재사용이 필요없을 경우, 흐름을 제어할 때 쓰일 수 있다.
   - Label의 Scope는 function Scope다.
   - break label;  => label의 맨 마지막으로 점프
      - loop문에서는 label을 생략할 수 있는데, 이는 엔진에서 label명의 자동으로 지정해주기 때문이다. (auto labeling), 현대의 loop문에는 auto labeling 기능외에도 stack clear라는 기능이 있는데 강의에서는 패스(확인필요)
   - continue label; => label의  처음위치로점프

- Function Scope
   - 사전 지식: 변수의 정의 (프로그래밍 언어론 개념)
      - 변수의 기본요소: 메모리 주소, 데이터의 크기
      - 변수의 특징: 라이프사이클, 접근제어(Scope)
      - 자바스크립트에서 Scope는 변수의 라이프 사이클과 접근제어를 포함하는 개념
   - 변수의 체계
     - 함수의 인자, 지역변수, 블록스코프 변수, 멤버변수
     - 자유변수와 클로저
        - 자유변수: 자기를 기준으로 자기가 알 수 없는 변수 (ex, 함수 => 지역변수와 인자가 아닌 변수)
        - 클로저: 쓸 수 있는 자유변수들이 실제로 사용될 수 있는 공간(블럭등)
          (ex. 함수의 자유변수(scope 바깥의 변수)를 사용할 때 클로저 => 함수)
     - 쉐도잉: Scope 바깥의 변수와 안의 변수가 이름이 동일할 때

- Lable 특징
  - Block Range
  - Goto Last
  - label은 코드 상단의 위치로 이동할 수 없다(?)

- Switch문

```javascript
switch (식) {
  case 식: 문
  default: 문
```

  - switch문에 나오는 블럭은 일반적인 중문이 아니라 switch문에 포함된 특수 블럭(switch label block)이다.

- continue와 break가 쓰이는 위치
  - iteration set
  - label set
  - switch set
- label/continue/break는 고전 프로그래밍 언어부터 쓰인 기본적인 흐름제어 방법이다.

### 스펙 보는 방법
매번 동영상을 보면서 느끼는 거지만, 아마 이 동영상 시리즈를 다 보게되도
강사가 애기해준 내용들을 다 기억하지 못할 뿐더러, 새로운 문제가 닥치면 강사처럼 내가 그걸 해결할 능력이 있을까? 
강사가 강의내용을 배운 방법(고기잡는방법)들을 공부 해야할 거 같고, 그 중의 하나가 언어의 스펙을 참고하는 것이다.

하지만 여기서 또 중요한 것은, 스펙은 어떻게 문법이 구성이 되어 있는지(즉, 문법적으로 틀리고 맞는지)를 가장 정확하게 확인하는 방법이지, 그 문법을 어떻게 사용해야 하는지까지 알려주지 않는다. 

#### 도전! Switch statement를 언어 스펙에서 확인해보기
- [Javascript](https://www.ecma-international.org/ecma-262/8.0/index.html#sec-switch-statement) 
- [Java](https://docs.oracle.com/javase/specs/jls/se9/html/jls-14.html#jls-14.11)
- [Python](https://docs.python.org/3/reference/compound_stmts.html#the-if-statement)
   - 파이썬에 switch statement가 없다는 것을 처음 알았다. 그래서 if문으로 대체

**Comment by deokju** [comment]
# INTERFACE

**javascript** 의 interface은 **java**와는 완전히 ***~~같다.~~*** 다르다.
흔히 나와 내 주변에서 알고 있는 interface는 java의 interface이다.
그럼 javascript의 interface란 무엇인가?

## 뜻
**사양**에 맞는 값과 연결된 속성키의 세트
어떤 Object라도 인터페이스의 정의를 충족시킬 수 있다.
하나의 Object는 여러개의 인터페이스를 충족시킬 수 있다.

## 사양(specification)
 인터페이스가 어떤 값을 가지고 어떤 속성을 가지는지를 정의한것
java는  java파일로 사양을 정의 할 수 있지만 javascript는 불가능 하다.


# javascript 내장되어 있는 인터페이스
interface 중에는 사용자가 정의해서 하는것 이외에도 javascript 엔진 자체에 내장(?)되어 있는것들도 있다.
#### Iterator
Iterator 인터페이스를 구현하는 객체는 아래 표1의 속성을 포함 해야 됩니다. 이러한 객체는 표2의 속성도 구현할 수 있습니다.
#### 표1
| Property       |value                          |Requirements				   |
|----------------|-------------------------------|-----------------------------|
|next			 |_IteratorResult_ type          |반환 된 객체는 iteratorResult interface type을 구현해야 합니다. Iterator의 다음 메소드에 대한 이전 호출이 done 속성이 true 인 IteratorResult 객체를 반환하면 해당 객체의 다음 메소드를 호출 할 때마다 done 속성이 true 인 IteratorResult 객체도 반환해야합니다.           |
#### 표2
| Property       |value                          |Requirements				   |
|----------------|-------------------------------|-----------------------------|
|_return_		 	 |_IteratorResult_           |반환 된 객체는 IteratorResult 인터페이스를 준수해야합니다. 이 메소드를 호출하면 (자), 호출 원이 Iterator에 대한 다음의 메소드 호출을 더 이상 실시하지 않는 것을 Iterator 객체에 통지합니다. 반환 된 IteratorResult 객체는 일반적으로 값이 true 인 done 속성과 반환 메서드의 인수로 전달 된 값을 갖는 value 속성을가집니다. 그러나이 요구 사항은 시행되지 않습니다.          |
|_throw_			 |_IteratorResult_   		 |반환 된 객체는 IteratorResult 인터페이스를 준수해야합니다. 이 메소드를 호출하면 (자), 호출 원이 에러 상태를 검출했다고 Iterator 객체에 통지합니다. 인수는 오류 조건을 식별하는 데 사용될 수 있으며 일반적으로 예외 오브젝트입니다. 일반적인 응답은 전달 된 값을 인수로 던지는 것입니다. 메서드가 throw되지 않으면 반환 된 IteratorResult 객체는 일반적으로 값이 true 인 done 속성을 갖습니다.

## code
```javascript
const  iterator  = {
	data:[1,2,3,4],
	next(){
		return {
			done : this.data.length ===  0,
			value: this.data.pop()
		};
	}
};
```

#### ITERABLE 인터페이스
1. ITERABLE 인터페이스는 _Symbol.iterator_ 라는 키를 가집니다.
2. 값으로 인자를 받지 않고 *ITERATOR* 인터페이스를 구현한 Object를 반환하는 함수가 옵니다.

## code
```javascript
const  iterator  = {
	data:[1,2,3,4],
	next(){
		return {
			done : this.data.length ===  0,
			value: this.data.pop()
		};
	}
};

const  iterable  = {
	[Symbol.iterator]() {
		return  iterator;
	}
};
```

# 객체지향
#### 캡슐화 code
 외부(사용하는 입장)에서 내부에서 일어나는 작업을 알 수 없게 하는것.
 내부에 변화가 생겨도 외부는 변하지 않는다.(격리)

**Comment by raycho206** [comment]
**코드스피츠 73 - 2회차 (2/2) 리뷰**

레이블은 흐름 제어의 기본이다.

If (식) 옵셔널
: 해도 그만 안해도 그만
If (식) ;
else ;

If (c === 1) {
} else if (c === 2) {
} else if (c === 3) {
} else {
}
이것도..
If (c === 1) {
} else {
    If (c === 2) {
    } else {
        If (c === 3) {
        } else {
        }
    }
}
이것도...
If (c > 5) {
} else switch (c) {
}
이것도...
If (c > 5) {
} else for (;;) {
}

if (c > 5) {
} else;
모두 문법에 맞다

else if 문은 위험한 코드이니 사용하지 말자
니가 컴파일러이면 써라 ㅋㅋ

병행조건 or 내가 평가해야 되는 식이 동등하면 switch문 사용

내가 평가해야 되는 식이 중첩 or if 중첩은 서브집합일 때 if else 문 사용

If (식) {
} else {
}
여기서 else 문에 if문이 들어오면 반드시 else로 끝나라

default가 없는 switch문은 사용하지 말자

“”, false, 0, undefined, null, Nan // falsy
for (선언문 or 식 or 공문; truthy or 공문; ex) {

}
for문에서 조건식에서 공문은 truthy이다

while or do while 을 사용할 때는
while(여기에 나오는게) {
    여기에도 나와야 함
}

let a = act.method().c;
while (a) {
    a = act.method().c;
}
이렇게 조건식에 나오는게 while문의 body에도 나와야 한다

35:10초 이해안됨

do a++; while (a);
