### ISSUE TITLE
[3차 스터디] 3월 17일(토) 저녁 9시 - 온라인

### ISSUE THREAD

**Issue by tea7day** [nomins/codespitz#5]
## 일정 (온라인)
- 3/12(월) `오후 10시 ~ 12시 (2시간)`

## 사전 준비사항
- 화상채팅 프로그램
  - [TeamViewer](https://www.teamviewer.com/en/download/windows/), [Skype](http://skype.daesung.com/eng/main.asp)
- 마이크 또는 마이크 되는 이어폰

## 진행 내용
- [코드스피츠 73 - 3회차 리뷰](https://www.youtube.com/watch?v=GhAkc00TvZs&index=4&list=PLBA53uNlbf-tKPtxR85LmXFYk0pNF8-Og) - `덕주`
- [코드스피츠 73 - 4회차 리뷰](https://www.youtube.com/watch?v=Ufh_E2Y090k&list=PLBA53uNlbf-tKPtxR85LmXFYk0pNF8-Og&index=3) - `원종`
- [코드스피츠 73 - 5회차 리뷰](https://www.youtube.com/watch?v=BeFekctVoq0&index=2&list=PLBA53uNlbf-tKPtxR85LmXFYk0pNF8-Og) - `승현`

## 참가 예정자
- 승현, 원종, 덕주

**Comment by deokju** [comment]
# nomi's codespitz 73 3회-2 부(ES6 + LOOP)
#### Array !== Object
#### ES6 *이전* LOOP
statement 를 통한 flow control에 집중

#### ES6 *이후*  LOOP
object 상태를 통하여 지연, 값, 캡슐화 LOOP


## 내장반복처리기
#### 예제에 사용되는 공통 iterable Object
```javascript
const  iter  = {
	[Symbol.iterator] (){return  this;},
	data:[1,2,3,4],
	next(){
			return {
					done : this.data.length ==  0,
					value: this.data.pop()
			};
	}
}
```
#### Array destructuring ~~(배열해체)~~ iterator 해체
```javascript
const[a,...b] =  iter;
console.log(a); // 1
console.log(b); // [2,3,4]
```
#### Spread (펼치기)

```javascript
const a =  [...iter];
console.log(a); // [1,2,3,4]
```

#### Rest Parameter(나머지인자)
함수 선언시 `...`  을 사용해야지만 Rest Parameter로 인식한다.
 ```javascript
const test = (...arg)=>console.log(arg);
```

#### For of
 ```javascript
for(const v of iter){
	console.log(v);
}
```
기존의 for는 for에 대한 제어권을 for문 안에 작성해야 하지만  **for of**는 iter Object의 **done** 메소드에 달려있다.
####  THIS ~~(담배)~~
javascript에서의 this는 java와 다른 의미를 가짐
**Java** : 현재 인스턴스를 가리킴.
**Javascript** : 동적 context를 의미함
 function 내에서 this를 쓰는건 좋지 않음. 그때 그때 호출하는쪽에 의해서 this가 가지는 의미가 달라지기때문에!
 ES6 이후 class 내에서만 this를 사용을 권장함.

**Comment by tea7day** [comment]
완료
- 03/18 23:00 ~ 01:00

4화(원종), 5화(승현) 발표는 차주로 연기
